# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelDemo', '0002_auto_20170721_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='L', max_length=1),
        ),
    ]
